### ISSUE TITLE
Final step, build-plugins.sh, fails with error

### ISSUE THREAD

**Issue by mikewesten** [Selur/hybrid-vapoursynth-addon#16]
$ bash build-plugins.sh
error: missing a local installation of FFmpeg libraries and Vapoursynth in `/home/my-user-name/opt/vapoursynth'
Have you forgotten to run `build-vapoursynth.sh' before ?

The previous $bash build-vapoursynth.sh command executed and completed and created an opt directory with some contents within my home directory.

I'm using Ubuntu 24.04 and have the latest Hybrid (Linux) installation from official download site

It's as though the 'build-vapoursynth.sh' script failed to put everything where it's supposed to be in order for the 'build-plugins.sh' script to execute properly. I followed instructions very closely so I'm really not certain what went wrong or why this occurs.

**Comment by Selur** [comment]
Strange.
Did you use the scripts from the Ubuntu2404 branch https://github.com/Selur/hybrid-vapoursynth-addon/tree/Ubuntu2404 ? 
or from the main branch?

**Comment by mikewesten** [comment]
No, I used the master branch ubuntu1804 but I will try now with the ubuntu2404 branch.

Okay, I extracted hybrid-vapoursynth-addon-Ubuntu2404.zip and moved into it
With this I get an error mid-compile on step one

$bash build-vapoursynth.sh
`configure: error: expected an absolute directory name for --prefix: "/home/my-user-name/opt/vapoursynth"
Error configuring 'zimg'.
`
I'll play around with it a little this weekend see if I can figure out what's wrong. There's no hurry at all.

**Comment by protvis74** [comment]
I found the little error. The $prefix strings in the configure options were wrongly escaped. I have corrected that and created a pull request.

To fix this you have to remove the backslashes.

 configure_options="--prefix=\"$VSPREFIX\"  ->  configure_options="--prefix="$VSPREFIX"

**Comment by mikewesten** [comment]
Yes that fixed it. Successfully installed all but one plugin (Akarin)
Hybrid is still showing a greyed out synth chooser under the filters tab though.
It doesn't appear to be aware of the existence of the plugins I've just installed.
I'm sure there's a simple final step to accomplish this but I'm unaware of what that final step is.

**Comment by mikewesten** [comment]
@protvis74 I was able to correct the mistake. I had performed my install using .opt (hidden folder syntax) rather than opt
Post-install I went through the changed the directory name to from .opt to opt as well as the paths entries in .bashrc and .profle, and now Hybrid is able to find it. I would prefer to have a hidden opt folder in my home directory but this is okay for now.

However I'm not able to perform an encode yet due to the (byteSize: 0byte) error. 
Are you familiar with this error?
I'll have to troubleshoot this soon.
I played about with changing the temp folder location as well as making the temp the same as my output folder. No luck so far.

**Comment by Selur** [comment]
*  One can use custom paths, read: [[INFO] *hidden* Hybrid options,...](https://forum.selur.net/thread-10.html). The debug output is often the most important thing. The normal log is useless if you need help, since it is purely for 'user amusement'. Which why it starts with:  
> This log is only intended for user information. 
> It should not be part of a bug/problem report!!"
* [Support](https://www.selur.de/support) lists what is usually needed to get at the bottom of issues. '_video crashed:' sounds like there is some problem with the encoder call or the piping, (Would need a debug output to know more.) I assume the Vapoursynth Preview works fine in Hybrid.

**Comment by mikewesten** [comment]
No worries. I included the line 

> SystemPluginDir=/home/my-user-name/opt/vapoursynth/vsplugins

in `/home/my-user-name/.config/vapoursynth/vapoursynth.conf`

now encoding works as expected.
I will bring any further support questions to the forum.
Thanks for building this great app and extending it's compatibility to Linux.
